site_name: Trésor des Demoiselles
site_author: Nicholas Cornia
repo_url: https://github.com/NicholasCorniaOrpheus/tresor-des-demoiselles
nav:
  - Home: index.md
  - Knowledge Graph: knowledge_graph.md
  - Contributors: contributors.md
  - References: references.md

plugins:
  - search

extra_css:
  - assets/css/extras.css

extra_javascript:
  - assets/js/CETEI.js
  - https://cdnjs.cloudflare.com/ajax/libs/openseadragon/4.1.0/openseadragon.min.js
  - https://d3js.org/d3.v7.min.js 
  - assets/js/openseadragon-init.js
  - assets/js/d3-graph.js

theme:
  name: material
  # custom_dir: overrides
  language: en
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    admonition:
      abstract: fontawesome/solid/book
      note: fontawesome/solid/note-sticky
      quote: fontawesome/solid/quote-left

  font:
      text: Crimson Pro
  palette:
    - scheme: slate
      primary: custom
      default: custom
      footer: custom
      accent: custom
      
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - search.share
    - toc.integrate


copyright: Copyright &copy; 2026 Orpheus Instituut, Resounding Libraries

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NicholasCorniaOrpheus
      name: GitHub repository
  social:
    - icon: material/music-note
      link: https://orpheusinstituut.be/
      name: Orpheus Instituut

markdown_extensions:
  - footnotes
  - tables
  - attr_list
  - admonition
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # icons extension!
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
